import continuous_differentiable_maps_nonlinear_functional_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace continuous_differentiable_maps_nonlinear_functional_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end continuous_differentiable_maps_nonlinear_functional_theorem_canonical_lane_mathlib
end HautevilleHouse
